### ISSUE TITLE
Could you please update the packages?

### ISSUE THREAD

**Issue by cyrinux** [grillo-delmal/inochi-creator-rpm#1]
Hi ! 

Thanks a lot for this copr, could you please update to the last version ? I'm looking an updated version for arm64.

**Comment by grillo-delmal** [comment]
Sure, gimme some time to undust my scripts and I'll get it done ;)

Btw, the official Flatpak release should work on arm64 (I say should cos it doesn't work on my RPi4, but it might work for you)

**Comment by grillo-delmal** [comment]
Updated the inochi-creator package and confirmed that it works on my RPi4 :)

**Comment by grillo-delmal** [comment]
Bonus: I also updated https://github.com/grillo-delmal/inochi-session-rpm to 0.8.3, seems to run on my RPi4 too

**Comment by cyrinux** [comment]
Thank you so much, as an idea, maybe you can add an automatic update like I did on my copr ? An update script per repo to get last tag or release, git commit depend, and some github actions 😺 

https://github.com/cyrinux/misc/

I took model on solopasha work.

https://github.com/solopasha/hyprlandRPM/

**Comment by grillo-delmal** [comment]
Thanks for the references :grinning:  

I already have experience automating deployments :wink: . I helped to build the [official inochi2d flathub workflow](https://github.com/flathub/com.inochi2d.inochi-creator) and I have a personal one for [nightly flatpak dev releases](https://github.com/grillo-delmal/inochi2d-flatpak-devtest) ( x86_64 only though ) but I haven't gone around checking on how to do them for COPR builds yet, so this helps :yum: . 

I was planning to automate this one at some point though, but I was waiting for https://github.com/dlang/dub/issues/1473 to get resolved. My main problem is that this package depends on many bundled libraries that can't get packaged as a standalone package because the dlang package manager (dub) doesn't support a way to use libraries stored in a read-only path (like the system).

**Comment by cyrinux** [comment]
I see, great, thanks for the explain @grillo-delmal !
Will try to do a puppet with OpenSeeFace now, sadly there is no package for this one 😝

**Comment by grillo-delmal** [comment]
> I see, great, thanks for the explain @grillo-delmal ! Will try to do a puppet with OpenSeeFace now, sadly there is no package for this one 😝 

OpenSeeFace is not hard to use on Fedora, all the dependencies are actually available in the distro right now.  I don't know if it works on arm64 though, you can try running it through this code

```sh
dnf install python-onnxruntime python-opencv python-pillow python-numpy
git clone git@github.com:emilianavt/OpenSeeFace.git
cd OpenSeeFace
python facetracker.py -c 0 -W 1280 -H 720 --discard-after 0 --scan-every 0 --no-3d-adapt 1 --max-feature-updates 900er 
```
You can toy with facetracker.py parameters to select a different video source, port, frequency, model....

At some point I was planning on packaging that too, but I lost interest along the way because I started using a different solution for facetracking.

https://ar14.itch.io/puppetstring

It has more options and a propper UI, but it's not open source and only works on x86_64 on Linux :/. I will ask the dev if he plans to build for arm64.

> By the way, there is something special that prevent enable an arm64 version of flatpak? Just out of curiosity.

It's actually enabled and you can test it if you want

```sh
flatpak install flathub com.inochi2d.inochi-creator
```

it just doesn't work on my RPi4, it shows problems regarding OpenGL or something related (I don't remember rn), but I don't have any other device to test on to see if it's just my env xD. I imagine that it has to do with the base image we are using or something related, but I wouldn't know how to correctly debug that...

**Comment by cyrinux** [comment]
Oh thanks you, I was just trying tuning param for facetracker.py, I install it in a python virtualenv for the moment. It works, will try with packaged lib also.
[ar14.itch.io/puppetstring](https://ar14.itch.io/puppetstring) looks very cool, I didnt spot this one, but yeah, I only have my asahi linux macbook now under arm64 arch so, thanks for asking to the dev !
About no open-source, I just order mannequin, will try to run it under macosx, I feel like it the only tools to easily create own character, I'm right ?
Thanks for helping me, It looks a wide world, lot of tools, I'm trying to find the good toys to use only linux - aarch64/arm64 and android.
I already tried to integrated in OBS the puppet with the inochi2d-session with green background then a chroma key filter. It works great, even if I understand maybe this "prout2" plugin for windows would be better, if I was a windows user.

**Comment by grillo-delmal** [comment]
Actually, the author from puppetstring is also the author of mannequin xD. From what I understand, Luna (inochi2d's proyect owner) does plan to add an integrated tracking solution to session at some point in the future, but that feature is burried under other priorities, so ar14 decided to build puppetstring in the meantime. 

If you have more questions regarding inochi2d, I would recommend you to join the discord server. There is not much activity rn cos Luna is busy with RL stuff and building a new env to rewrite the UI, but there are people around that can help you with your questions (including me).

https://discord.com/invite/abnxwN6r9v
